-- insert the 1st 'admin' account
INSERT INTO FORUM_USER_PROFILE (USER_NAME, USER_PASSWORD, USER_ALIAS, USER_EMAIL, USER_TYPE, USER_LEVEL, USER_SIGNATURE, USER_AVATAR_PIC, USER_REGISTER_DATE, USER_LOGIN_STATUS) 
VALUES ('admin', 'password', 'administrator', 'admin@mail.com', 'admin', 3, 'Administrator!', 'avatar_0.jpg', CURRENT_TIMESTAMP, 0);
-- insert the 1st test visitor 'marlio' account
INSERT INTO FORUM_USER_PROFILE (USER_NAME, USER_PASSWORD, USER_ALIAS, USER_EMAIL, USER_TYPE, USER_LEVEL, USER_SIGNATURE, USER_AVATAR_PIC, USER_REGISTER_DATE, USER_LOGIN_STATUS) 
VALUES ('marlio', 'password', 'jitao', 'jitao.liu82@gmail.com', 'common', 1, 'The world!...', 'avatar_0.jpg', CURRENT_TIMESTAMP, 0);
-- insert the 2nd test visitor 'test01' account
INSERT INTO FORUM_USER_PROFILE (USER_NAME, USER_PASSWORD, USER_ALIAS, USER_EMAIL, USER_TYPE, USER_LEVEL, USER_SIGNATURE, USER_AVATAR_PIC, USER_REGISTER_DATE, USER_LOGIN_STATUS)  
VALUES ('test01', 'password', 'test01', 'skymarlio@hotmail.com', 'common', 1, 'This is test01!', 'avatar_1.jpg', CURRENT_TIMESTAMP, 0);
-- insert the 3rd test visitor 'test02' account
INSERT INTO FORUM_USER_PROFILE (USER_NAME, USER_PASSWORD, USER_ALIAS, USER_EMAIL, USER_TYPE, USER_LEVEL, USER_SIGNATURE, USER_AVATAR_PIC, USER_REGISTER_DATE, USER_LOGIN_STATUS) 
VALUES ('test02', 'password', 'test02', 'jitao.liu82@gmail.com', 'common', 1, 'This is test02!', 'avatar_2.jpg', CURRENT_TIMESTAMP, 0);
-- create the 1st test post sample
INSERT INTO FORUM_POST (POST_TOPIC, POST_CONTENT, POST_ATTACHMENT_IMG, POST_MARK, POST_COMMENT_NUM, POST_LEVEL, POST_USER_ID, POST_TIME) 
VALUES ('Test post topic', '[color=red][s][u][i][b]Test post content[/b][/i][/u][/s][/color][br][color=green][b]Test post content[/b][/color][:)][:(]', null, 1, 1, 0, 2, CURRENT_TIMESTAMP);
-- create the 1st post comment for the 1st test post
INSERT INTO FORUM_POST_COMMENT (POST_COMMENT_POST_ID, POST_COMMENT_CONTENT, POST_COMMENT_USER_ID, POST_COMMENT_DATE, POST_COMMENT_MARK) 
VALUES (1, 'Test post comment 1-1', 3, CURRENT_TIMESTAMP, 1);
-- create a friend relation link between 'test02' and 'marlio'
INSERT INTO FORUM_FRIEND_LINK (FRIEND_LINK_HOST_USER_ID, FRIEND_LINK_CUST_USER_ID, FRIEND_LINK_MAP_DATE) 
VALUES (2, 4, CURRENT_TIMESTAMP);
INSERT INTO FORUM_FRIEND_LINK (FRIEND_LINK_HOST_USER_ID, FRIEND_LINK_CUST_USER_ID, FRIEND_LINK_MAP_DATE) 
VALUES (4, 2, CURRENT_TIMESTAMP);
-- append 20 messages from 'test01' to 'marlio'
INSERT INTO FORUM_MESSAGE (MESSAGE_SOURCE_USER_ID, MESSAGE_DESTINATION_USER_ID, MESSAGE_CONTENT, MESSAGE_TIME, MESSAGE_READ_FLAG) 
VALUES (3, 2, 'Hello, for test-01 (test01 to marlio) ...', CURRENT_TIMESTAMP, 0);
INSERT INTO FORUM_MESSAGE (MESSAGE_SOURCE_USER_ID, MESSAGE_DESTINATION_USER_ID, MESSAGE_CONTENT, MESSAGE_TIME, MESSAGE_READ_FLAG) 
VALUES (3, 2, 'Hello, for test-02 (test01 to marlio) ...', CURRENT_TIMESTAMP, 0);
-- append 20 messages from 'marlio' to 'test01'
INSERT INTO FORUM_MESSAGE (MESSAGE_SOURCE_USER_ID, MESSAGE_DESTINATION_USER_ID, MESSAGE_CONTENT, MESSAGE_TIME, MESSAGE_READ_FLAG) 
VALUES (2, 3, 'Hello, for test-01 (marlio to test01) ...', CURRENT_TIMESTAMP, 0);
INSERT INTO FORUM_MESSAGE (MESSAGE_SOURCE_USER_ID, MESSAGE_DESTINATION_USER_ID, MESSAGE_CONTENT, MESSAGE_TIME, MESSAGE_READ_FLAG) 
VALUES (2, 3, 'Hello, for test-02 (marlio to test01) ...', CURRENT_TIMESTAMP, 0);
