
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
VALUES ('admin', 'password', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
VALUES ('marlio', 'password', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
VALUES ('test01', 'password', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
VALUES ('test02', 'password', TRUE);

INSERT INTO USER_ROLES (USERNAME, ROLE)
VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO USER_ROLES (USERNAME, ROLE)
VALUES ('marlio', 'ROLE_ADMIN');
INSERT INTO USER_ROLES (USERNAME, ROLE)
VALUES ('marlio', 'ROLE_USER');
INSERT INTO USER_ROLES (USERNAME, ROLE)
VALUES ('test01', 'ROLE_USER');
INSERT INTO USER_ROLES (USERNAME, ROLE)
VALUES ('test02', 'ROLE_USER');
