
-- CREATE SCHEMA IF NOT EXISTS `jspforum` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE `jspforum`;

-- ===========================
-- Table of FORUM_USER_PROFILE
-- ===========================

DROP TABLE IF EXISTS `jspforum`.`FORUM_USER_PROFILE`;

CREATE TABLE IF NOT EXISTS `jspforum`.`FORUM_USER_PROFILE` (
	`USER_ID` INT NOT NULL AUTO_INCREMENT, 
	`USER_NAME` VARCHAR(30) NOT NULL, 
	`USER_PASSWORD` VARCHAR(200) NOT NULL, 
	`USER_ALIAS` VARCHAR(30) NOT NULL, 
	`USER_EMAIL` VARCHAR(50) NOT NULL, 
	`USER_TYPE` VARCHAR(50) NOT NULL, 
	`USER_LEVEL` INT NOT NULL, 
	`USER_SIGNATURE` VARCHAR(100) NULL, 
	`USER_AVATAR_PIC` VARCHAR(200) NOT NULL, 
	`USER_REGISTER_DATE` DATETIME NOT NULL, 
	`USER_LOGIN_STATUS` INT NOT NULL DEFAULT 0, 
	PRIMARY KEY (`USER_ID`) 
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci 
ENGINE = InnoDB 
COMMENT = 'The main entity for the user of forum';

-- ===================
-- Table of FORUM_POST
-- ===================

DROP TABLE IF EXISTS `jspforum`.`FORUM_POST`;

CREATE TABLE IF NOT EXISTS `jspforum`.`FORUM_POST` (
	`POST_ID` INT NOT NULL AUTO_INCREMENT, 
	`POST_TOPIC` VARCHAR(150) NOT NULL, 
	`POST_CONTENT` VARCHAR(1000) NOT NULL, 
	`POST_ATTACHMENT_IMG` VARCHAR(200) NULL, 
	`POST_MARK` INT NOT NULL, 
	`POST_COMMENT_NUM` INT NULL, 
	`POST_LEVEL` INT NOT NULL, 
	`POST_USER_ID` INT NOT NULL, 
	`POST_TIME` DATETIME NOT NULL, 
	PRIMARY KEY (`POST_ID`), 
	INDEX `fk_FORUM_POST_FORUM_USER_PROFILE` (`POST_USER_ID` ASC), 
	CONSTRAINT `fk_FORUM_POST_FORUM_USER_PROFILE` FOREIGN KEY (`POST_USER_ID`) REFERENCES `jspforum`.`FORUM_USER_PROFILE` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION 
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci 
ENGINE = InnoDB 
COMMENT = 'POST POOL (Main POST Entity)';

-- ===========================
-- Table of FORUM_POST_COMMENT
-- ===========================

DROP TABLE IF EXISTS `jspforum`.`FORUM_POST_COMMENT`;

CREATE TABLE IF NOT EXISTS `jspforum`.`FORUM_POST_COMMENT` (
	`POST_COMMENT_ID` INT NOT NULL AUTO_INCREMENT, 
	`POST_COMMENT_POST_ID` INT NOT NULL, 
	`POST_COMMENT_CONTENT` VARCHAR(1000) NOT NULL, 
	`POST_COMMENT_USER_ID` INT NOT NULL, 
	`POST_COMMENT_DATE` DATETIME NOT NULL, 
	`POST_COMMENT_MARK` INT NULL, 
	PRIMARY KEY (`POST_COMMENT_ID`), 
	INDEX `fk_FORUM_POST_COMMENT_FORUM_POST` (`POST_COMMENT_POST_ID` ASC), 
	INDEX `fk_FORUM_POST_COMMENT_FORUM_USER_PROFILE` (`POST_COMMENT_USER_ID` ASC), 
	CONSTRAINT `fk_FORUM_POST_COMMENT_FORUM_POST` FOREIGN KEY (`POST_COMMENT_POST_ID`) REFERENCES `jspforum`.`FORUM_POST` (`POST_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION, 
	CONSTRAINT `fk_FORUM_POST_COMMENT_FORUM_USER_PROFILE` FOREIGN KEY (`POST_COMMENT_USER_ID`) REFERENCES `jspforum`.`FORUM_USER_PROFILE` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION 
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci 
ENGINE = InnoDB 
COMMENT = 'POST and POST Response : one to many';

-- ======================
-- Table of FORUM_MESSAGE
-- ======================

DROP TABLE IF EXISTS `jspforum`.`FORUM_MESSAGE`;

CREATE TABLE IF NOT EXISTS `jspforum`.`FORUM_MESSAGE` (
	`MESSAGE_ID` INT NOT NULL AUTO_INCREMENT, 
	`MESSAGE_SOURCE_USER_ID` INT NOT NULL, 
	`MESSAGE_DESTINATION_USER_ID` INT NOT NULL, 
	`MESSAGE_CONTENT` VARCHAR(500) NOT NULL, 
	`MESSAGE_TIME` DATETIME NOT NULL, 
	`MESSAGE_READ_FLAG` INT NOT NULL DEFAULT 0, 
	PRIMARY KEY (`MESSAGE_ID`), 
	INDEX `fk_FORUM_MESSAGE_FORUM_USER_PROFILE1` (`MESSAGE_SOURCE_USER_ID` ASC), 
	INDEX `fk_FORUM_MESSAGE_FORUM_USER_PROFILE2` (`MESSAGE_DESTINATION_USER_ID` ASC), 
	CONSTRAINT `fk_FORUM_MESSAGE_FORUM_USER_PROFILE1` FOREIGN KEY (`MESSAGE_SOURCE_USER_ID`) REFERENCES `jspforum`.`FORUM_USER_PROFILE` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION, 
	CONSTRAINT `fk_FORUM_MESSAGE_FORUM_USER_PROFILE2` FOREIGN KEY (`MESSAGE_DESTINATION_USER_ID`) REFERENCES `jspforum`.`FORUM_USER_PROFILE` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci 
ENGINE = InnoDB 
COMMENT = 'The simple message entity';

-- ==========================
-- Table of FORUM_FRIEND_LINK
-- ==========================

DROP TABLE IF EXISTS `jspforum`.`FORUM_FRIEND_LINK`;

CREATE TABLE IF NOT EXISTS `jspforum`.`FORUM_FRIEND_LINK` (
	`FRIEND_LINK_ID` INT NOT NULL AUTO_INCREMENT, 
	`FRIEND_LINK_HOST_USER_ID` INT NOT NULL, 
	`FRIEND_LINK_CUST_USER_ID` INT NOT NULL, 
	`FRIEND_LINK_MAP_DATE` DATETIME NOT NULL, 
	PRIMARY KEY (`FRIEND_LINK_ID`), 
	INDEX `fk_FORUM_FRIEND_LINK_FORUM_USER_PROFILE1` (`FRIEND_LINK_HOST_USER_ID` ASC), 
	INDEX `fk_FORUM_FRIEND_LINK_FORUM_USER_PROFILE2` (`FRIEND_LINK_CUST_USER_ID` ASC), 
	CONSTRAINT `fk_FORUM_FRIEND_LINK_FORUM_USER_PROFILE1` FOREIGN KEY (`FRIEND_LINK_HOST_USER_ID`) REFERENCES `jspforum`.`FORUM_USER_PROFILE` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION, 
	CONSTRAINT `fk_FORUM_FRIEND_LINK_FORUM_USER_PROFILE2` FOREIGN KEY (`FRIEND_LINK_CUST_USER_ID`) REFERENCES `jspforum`.`FORUM_USER_PROFILE` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci 
ENGINE = InnoDB 
COMMENT = 'Friendship Linking';

-- ===================================
-- Table of FORUM_FRIEND_JOINT_REQUEST
-- ===================================

DROP TABLE IF EXISTS `jspforum`.`FORUM_FRIEND_JOINT_REQUEST`;

CREATE TABLE IF NOT EXISTS `jspforum`.`FORUM_FRIEND_JOINT_REQUEST` (
	`FRIEND_JOINT_REQUEST_ID` INT NOT NULL AUTO_INCREMENT, 
	`FRIEND_JOINT_REQUEST_FROM_USER_ID` INT NOT NULL, 
	`FRIEND_JOINT_REQUEST_TO_USER_ID` INT NOT NULL, 
	`FRIEND_JOINT_REQUEST_REMARK` VARCHAR(100) NULL, 
	`FRIEND_JOINT_REQUEST_DATE` DATETIME NOT NULL, 
	`FRIEND_JOINT_REQUEST_STATUS` VARCHAR(30) NOT NULL, 
	PRIMARY KEY (`FRIEND_JOINT_REQUEST_ID`), 
	INDEX `fk_FORUM_FRIEND_JOINT_REQUEST_FORUM_USER_PROFILE1` (`FRIEND_JOINT_REQUEST_FROM_USER_ID` ASC), 
	INDEX `fk_FORUM_FRIEND_JOINT_REQUEST_FORUM_USER_PROFILE2` (`FRIEND_JOINT_REQUEST_TO_USER_ID` ASC), 
	CONSTRAINT `fk_FORUM_FRIEND_JOINT_REQUEST_FORUM_USER_PROFILE1` FOREIGN KEY (`FRIEND_JOINT_REQUEST_FROM_USER_ID`) REFERENCES `jspforum`.`FORUM_USER_PROFILE` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION, 
	CONSTRAINT `fk_FORUM_FRIEND_JOINT_REQUEST_FORUM_USER_PROFILE2` FOREIGN KEY (`FRIEND_JOINT_REQUEST_TO_USER_ID`) REFERENCES `jspforum`.`FORUM_USER_PROFILE` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci 
ENGINE = InnoDB
COMMENT = 'the friend joint request';

DROP VIEW `jspforum`.`V_POST_HAS_COMMENT`;

CREATE VIEW `jspforum`.`V_POST_HAS_COMMENT` AS 
SELECT 1 ID, count(*) NUM 
FROM FORUM_POST AS post JOIN FORUM_POST_COMMENT AS comment ON post.POST_ID = comment.POST_COMMENT_POST_ID 
WHERE lower(post.POST_TOPIC) LIKE '%test%';

