
CREATE TABLE USERS (
	USERNAME VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(45) NOT NULL,
	ENABLED TINYINT NOT NULL DEFAULT 1,
	PRIMARY KEY (USERNAME));

CREATE TABLE USER_ROLES (
	USER_ROLE_ID INT(11) NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(45) NOT NULL,
	ROLE VARCHAR(45) NOT NULL,
	PRIMARY KEY (USER_ROLE_ID));
